#!/bin/sh /etc/rc.common
# probe data post process start on boot
# Mon Nov  2 10:00:54 CST 2015 created by GaomingPan
#

START=98
STOP=60

start()
{
  /usr/sbin/probe_data_post &
}

stop()
{
  rst=`ps | grep post_mac_probe | cut -d "r" -f 1`
  if [ -n "$rst" ]
   then
    kill -9 $rst
 fi
}


